Presentation/ViewModels/LoginVM.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Presentation.ViewModels
{
    public class LoginVM
    {
        [Required]
        public string UserName { get; set; }
        [Required]
        public string Password { get; set; }
    }
}

Presentation/Controllers/AccountController.cs
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using Presentation.Identity;
using Presentation.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Presentation.Controllers
{
    public class AccountController : Controller
    {

        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;

        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set
            {
                _signInManager = value;
            }
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        private IAuthenticationManager AuthenticationManager
        {
            get
            {
                return HttpContext.GetOwinContext().Authentication;
            }
        }

        public ActionResult Login()
        {
            return PartialView("Login");
        }

        [HttpPost]
        public async Task<ActionResult> Login(LoginVM login)
        {

            if (ModelState.IsValid)
            {
                IdentityUser identityUser = await UserManager.FindAsync(login.UserName, login.Password);
                if (identityUser != null)
                {
                    SignInManager.SignIn(identityUser, false, true);
                    ViewBag.UserId = identityUser.Id;
                    ViewBag.UserName = identityUser.UserName;

                    return RedirectToAction("Main", "Home");
                }
                else
                {
                    ViewBag.LoginFailed = "Incorrect username or password";

                    return PartialView("Login", login);
                }

            }
            else
            {
                return PartialView("Login", login);
            }
        }

        public ActionResult Logout()
        {
            AuthenticationManager.SignOut();

            return RedirectToAction("Index", "Home");
        }
    }
}

Presentation/Controllers/BlogController.cs
using Data.Infrastructure;
using Data.Repositories;
using Model.Models;
using PagedList;
using Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Presentation.Controllers
{
    public class BlogController : Controller
    {

        IBlogsService blogsService;
        IUnitOfWork unitOfWork;
        IBlogRepository blogsRepository;
        IDbFactory dbFactory;

        public BlogController()
        {
            dbFactory = new DbFactory();
            unitOfWork = new UnitOfWork(dbFactory);
            blogsRepository = new BlogRepository(dbFactory);

            blogsService = new BlogsService(blogsRepository, unitOfWork);
        }
        // GET: Blog
        [Authorize]
        public ActionResult Index(int page, int size, int userId, string dateFrom, string dateTo, string filter = "")
        {
            DateTime _dateFrom = DateTime.MinValue;
            DateTime _dateTo = DateTime.Now;

            DateTime.TryParse(dateFrom, out _dateFrom);
            DateTime.TryParse(dateTo, out _dateTo);

            ViewBag.DateFrom = dateFrom;
            ViewBag.DateTo = dateTo;
            ViewBag.Filter = filter;

            List<Blog> blogs = blogsService.FindByUserPublishDateAndTitle(userId, filter, _dateFrom, _dateTo);
            IPagedList<Blog> pageListBlog = blogs.ToPagedList(page, size);


            return PartialView("Index", pageListBlog);


        }



        [Authorize]
        public ActionResult GetBlogs(int page, int size, int userId, string dateFrom, string dateTo, string filter = "")
        {
            DateTime _dateFrom = DateTime.MinValue;
            DateTime _dateTo = DateTime.Now;

            DateTime.TryParse(dateFrom, out _dateFrom);
            if (!DateTime.TryParse(dateTo, out _dateTo))
            {
                _dateTo = DateTime.Now;
            }

            

            ViewBag.DateFrom = dateFrom;
            ViewBag.DateTo = dateTo;
            ViewBag.Filter = filter;

            List<Blog> blogs = blogsService.FindByUserPublishDateAndTitle(userId, filter, _dateFrom, _dateTo);
            IPagedList<Blog> pageListBlog = blogs.ToPagedList(page, size);


            return PartialView("List", pageListBlog);



        }

    }
}

Presentation/Controllers/HomeController.cs
using Data.Infrastructure;
using Data.Repositories;
using Microsoft.AspNet.Identity;
using Presentation.Identity;
using Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Presentation.Controllers
{
    public class HomeController : Controller
    {



        // GET: Home
        public ActionResult Index()
        {

            return View();
        }

        public ActionResult Main()
        {
            return PartialView("Main");
        }

        [Authorize]
        public ActionResult Test()
        {
            return PartialView();
        }
    }
}

Presentation/Controllers/UsersController.cs
using AutoMapper;
using Data.Infrastructure;
using Data.Repositories;
using Presentation.Identity;
using Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Model.Models;
namespace Presentation.Controllers
{
    public class UsersController : Controller
    {
        IUsersService usersService;
        IUnitOfWork unitOfWork;
        IUserRepository usersRepository;
        IDbFactory dbFactory;
       
        public UsersController()
        {
            dbFactory = new DbFactory();
            unitOfWork = new UnitOfWork(dbFactory);
            usersRepository = new UserRepository(dbFactory);

            usersService = new UsersService(usersRepository, unitOfWork);
        }

        // GET: Users
        public ActionResult Index(int page, int count, string filter = "")
        {

            List<IdentityUser> users = Mapper.Map<List<User>, List<IdentityUser>>(usersService.FindByNameOrEmail(filter, page - 1, count));
            return PartialView("Index", users);
        }

        public ActionResult Profile(int userId)
        {
            IdentityUser user = Mapper.Map<User, IdentityUser>(usersService.FindById(userId));
            return PartialView("Profile", user);
        }


    }
}

Presentation/Views/Blog/Index.cshtml
@using Model.Models
@using PagedList.Mvc
@model  PagedList.IPagedList<Blog>
@{
    ViewBag.Page = "Index";
}
<div class="col-md-12">
    <div class="form-inline">



        @using (Ajax.BeginForm("GetBlogs", "Blog", null, new AjaxOptions()
        {
            HttpMethod = "GET",
            InsertionMode = InsertionMode.Replace,
            UpdateTargetId = "blogs",


        }, new { @class = "form form-horizontal" }))
        {

            @Ajax.ActionLink("Create a new Blog", "", null, new AjaxOptions() { }, new { @class = "btn btn-success" })
            <input type="hidden" name="page" value="1" />
            <input type="hidden" name="size" value="5" />
            <input type="hidden" name="userId" value="@Model[0].UserId" />
            @Html.TextBox("dateFrom", null, new { @class = "form-control", @type = "date" })
            @Html.TextBox("dateTo", null, new { @class = "form-control", @type = "date" })
            @Html.TextBox("filter", null, new { @class = "form-control" })

            <input type="submit" class="btn btn-primary" />
        }


    </div>

    <div id="blogs">
        @Html.Partial("List", Model);

    </div>



</div>

Presentation/Views/Blog/List.cshtml
@using Model.Models
@using PagedList.Mvc
@model  PagedList.IPagedList<Blog>
<table class="table table-bordered">
    <thead>
        <tr>
            <td>Title</td>
            <td>Summary</td>
            <td>Publishing date</td>
        </tr>
    </thead>
    @foreach (Blog item in Model)
    {
        <tr>
            <td>@item.Title</td>
            <td>@item.Summary</td>
            <td>@item.PublishDate.ToString("H:mm dd MMM yyyy")</td>

        </tr>
    }
</table>
@Html.PagedListPager(Model, page => Url.Action("GetBlogs", new { page, size = 5, userId = Model[0].UserId, dateFrom = ViewBag.dateFrom, dateTo = ViewBag.dateTo, filter = ViewBag.Filter }),
                                        PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(new AjaxOptions() { HttpMethod = "GET", InsertionMode = InsertionMode.Replace, UpdateTargetId = "blogs" }))

Presentation/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}


@if (User.Identity.IsAuthenticated)
{
    @Html.Partial("Main");
}
else
{
    @Html.Partial("~/Views/Account/Login.cshtml")
}

Presentation/Views/Home/Main.cshtml
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">


            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                    <a href="#">
                        <span class="glyphicon glyphicon-user"></span>
                        <strong>
                            Hey
                            @if (User.Identity.Name != "")
                            {

                                @User.Identity.Name
                            }
                            else
                            {
                                @ViewBag.UserName
                            }
                            ! - Logout
                        </strong>

                    </a>
                </li>
            </ul>

        </div>
    </div>
</div>
<div class="row">
    <div id="main">
        @Html.Action("Index", "Users", new { page = 1, count = 5, filter = "" })
    </div>
</div>

Presentation/Views/Home/Menu.cshtml
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">


            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                    <a href="#">
                        <span class="glyphicon glyphicon-user"></span>
                        <strong>
                            Hey
                            @if (User.Identity.Name != "")
                            {
                                @User.Identity.Name
                            }
                            else
                            {
                                @ViewBag.UserName
                            }
                            ! - Logout
                        </strong>

                    </a>
                </li>
            </ul>

        </div>
    </div>
</div>

Presentation/Views/Shared/_Layout.cshtml
@model Presentation.Identity.IdentityUser
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>

    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
</head>
<body>


    <div class="container body-content" id="app">

        @RenderBody()

        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.3.1.min.js"></script>

    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
    <script src="~/Scripts/custom.js"></script>
    @*<script src="~/Scripts/sammy-0.7.5.min.js"></script>
        <script src="~/Scripts/app/app.js"></script>*@

</body>
</html>

Presentation/Views/Users/Index.cshtml
@model List<Presentation.Identity.IdentityUser>

<div class="col-md-12">


    @using (Ajax.BeginForm("Index", "Users", null, new AjaxOptions() { HttpMethod = "GET", InsertionMode = InsertionMode.Replace, UpdateTargetId = "main" }, new { @class = "form form-horizontal" }))
    {
        <input type="hidden" name="page" value="1" />
        <input type="hidden" name="count" value="5" />
        <input type="text" name="filter" class="form-control" />
        <input type="submit" value="Search" class="btn btn-primary" />
    }



    <table class="table table-bordered">
        <thead>
            <tr>
                <td>Username</td>
                <td>Age</td>
                <td>Email</td>
                <td>Blogs</td>
            </tr>
        </thead>
        @foreach (Presentation.Identity.IdentityUser item in Model)
        {
            <tr>
                <td>@item.UserName</td>
                <td>@item.Age.ToString()</td>
                <td>@item.Email</td>
                <td>
                    @if (item.BlogCount != null)
                    {
                        @item.BlogCount.ToString();
                    }
                    else
                    {
                        0.ToString();
                    }

                </td>
                <td>


                    @Ajax.ActionLink("View", "Profile", "Users", new { userId = item.Id }, new AjaxOptions()
                    {
                        HttpMethod = "GET",
                        InsertionMode = InsertionMode.Replace,
                        UpdateTargetId = "main"
                    })
                </td>
            </tr>
        }
    </table>

</div>

Presentation/Views/Users/Profile.cshtml
@model Presentation.Identity.IdentityUser
<div class="col-md-12">
    <h3>@Model.UserName</h3>

    <div class="panel panel-default">
        <div class="panel-heading">User details</div>
        <div class="panel-body">
            <div class="form-inline">

                @Html.TextBoxFor(x => x.FirstName, new { @readonly = "readonly", @class = "form-control" })
                @Html.TextBoxFor(x => x.LastName, new { @readonly = "readonly", @class = "form-control" })

            </div>
        </div>
    </div>
</div>

@Html.Action("Index","Blog",new {page=1, size=5, userId = Model.Id, dateFrom = DateTime.MinValue, dateTo = DateTime.Now })